# Generated by Django 3.2.18 on 2023-08-05 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=256)),
                ('image', models.ImageField(upload_to='images/')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=256)),
                ('color', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('b+', 'B-'), ('ab-', 'AB+'), ('ab', 'AB')], default='o+', max_length=6)),
                ('gpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(4.0)])),
                ('religion', models.CharField(choices=[('christian', 'CHRISTIAN'), ('muslim', 'MUSLIM'), ('others', 'OTHERS')], default='christian', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('class_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FloatField(default=0)),
                ('exam', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.subject')),
            ],
        ),
    ]
