# Generated by Django 3.2.18 on 2023-08-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20230805_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='color',
            new_name='blood_group',
        ),
    ]
