# Generated by Django 3.2.18 on 2023-08-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('christian', 'CHRISTIAN'), ('muslim', 'MUSLIM'), ('others', 'OTHERS')], default='', max_length=20),
        ),
    ]
