# Generated by Django 3.2.18 on 2023-08-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_alter_student_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('', ''), ('o+', 'O+'), ('o-', 'O-'), ('b+', 'B-'), ('ab-', 'AB+'), ('ab', 'AB')], default='o+', max_length=6),
        ),
    ]
