# Generated by Django 3.2.18 on 2023-08-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_student_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='teacher_class',
            field=models.ForeignKey(default='Cleaner', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class'),
        ),
    ]
