# Generated by Django 3.2.18 on 2023-08-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_primary_school_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
