# Generated by Django 3.2.18 on 2023-08-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_alter_staff_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
