# Generated by Django 3.2.18 on 2023-08-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0017_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.ManyToManyField(blank=True, choices=[('English', 'ENGLISH'), ('French', 'FRENCH')], related_name='_schoolapp_student_language_+', to='schoolapp.Student'),
        ),
    ]
