# Generated by Django 3.2.18 on 2023-08-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0018_student_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='language',
        ),
    ]
