# Generated by Django 3.2.18 on 2023-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0019_remove_student_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
