# Generated by Django 3.2.18 on 2023-08-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0022_auto_20230809_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='expreience',
            new_name='experience',
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
